### ISSUE TITLE
Overriding standard identity resources

### ISSUE THREAD

**Issue by sipe90** [Soluto/oidc-server-mock#123]
I am trying to mock an identity provider which modifies or adds to the standard "profile" and "email" scopes. I tried to mock this behavior by defining these scopes in the identity resources configuration, but the server crashes with `Unhandled exception. System.ArgumentException: Identity resources must not contain duplicate names`

Could it be possible to make it so that you could modify these scopes in the identity resources configuration?

**Comment by AleF83** [comment]
Hey,
Can you please provide your configuration?
And another question, why do you want to define these scopes?

**Comment by sipe90** [comment]
As I stated before, I want to mock an OIDC server which has the "profile" and "email" scopes, but the claims they contain differ from the standard. The identity resources configuration looks something like this (removed some less generic claims for privacy reasons):
```yaml
 - Name: profile
   ClaimTypes:
    - firstname
    - lastname
    - sub
    - al
    - am
    - regionName
    - grp
    - language
    - sid
- Name: smallprofile
  ClaimTypes:
    - firstname
    - lastname
    - sub
    - al
    - am
    - language
    - sid
 - Name: email
   ClaimTypes:
     - mail
- Name: location
  ClaimTypes:
    - ipaddr
    - country
    - remote
- Name: groups
  ClaimTypes:
    - grp
- Name: profileoidc
  ClaimTypes:
    - sub
    - given_name
    - family_name
    - email
    - al
    - am
    - sid
```
As a workaround I could just create custom scopes like "custom.profile" and "custom.email" but then I would need to have to use different scopes in dev/testing and production.
