### ISSUE TITLE
How do I use the 'introspect' url?

### ISSUE THREAD

**Issue by forceedge01** [Soluto/oidc-server-mock#135]
Hello,

I am trying to introspect an access token before using it. My API needs to call on the identity server's introspect url. As I understand it, I need to create an API resource and tie the secret with this resource, but so far no example has worked. 

I've added 
ApiSecrets:
- a-secret

in the yaml configuration in the API Resources block, but to no avail. Is the mock configured to read Api Secrets from the inline configuration?

**Comment by forceedge01** [comment]
More info - The server spits out the following:

```
[08:14:50 Debug] Duende.IdentityServer.Validation.ISecretsListParser
oidc-server-mock  | Secret id found: some-app
oidc-server-mock  | 
oidc-server-mock  | [08:14:50 Debug] Duende.IdentityServer.Validation.HashedSharedSecretValidator
oidc-server-mock  | No matching hashed secret found.
oidc-server-mock  | 
oidc-server-mock  | [08:14:50 Debug] Duende.IdentityServer.Validation.ISecretsListValidator
oidc-server-mock  | Secret validators could not validate secret
oidc-server-mock  | 
oidc-server-mock  | [08:14:50 Error] Duende.IdentityServer.Validation.ApiSecretValidator
oidc-server-mock  | API validation failed.
oidc-server-mock  | 
oidc-server-mock  | [08:14:50 Error] Duende.IdentityServer.Endpoints.IntrospectionEndpoint
oidc-server-mock  | API unauthorized to call introspection endpoint. aborting.
```

Clearly trying to validate, but it isn't able to. My docker-compose looks like this:

```
API_RESOURCES_INLINE: |
        - Name: some-app
          Scopes:
            - some-app-scope-1
            - some-app-scope-2
          ApiSecrets:
            - not-a-secret-after-all
```

And I am making a POST call to the /connect/introspect is with:

client_id: some-app
client_secret: not-a-secret-after-all
token: {the-token}

I've tried the client_secret with a hashed version as well.
