### ISSUE TITLE
Custom claims not in id_token or /userinfo response

### ISSUE THREAD

**Issue by cburmeister** [Soluto/oidc-server-mock#26]
I can't seem to get custom claims to show up in the `id_token` nor the `/userinfo` response.

Here's my configuration:
```yaml
  mock-idp:
    image: soluto/oidc-server-mock:0.1.2
    ports:
      - "4014:80"
    environment:
      CLIENTS_CONFIGURATION_INLINE: |
        [
          {
            "AllowAccessTokensViaBrowser": true,
            "AllowedGrantTypes": [
              "authorization_code",
              "refresh_token"
            ],
            "AllowedScopes": [
              "openid",
              "profile",
              "email"
            ],
            "AllowPlainTextPkce": true,
            "AlwaysIncludeUserClaimsInIdToken": true,
            "ClientId": "example-client",
            "ClientSecrets": [
              "example-password"
            ],
            "RedirectUris": [
              "http://client.docker:5050/idp/callback/"
            ],
            "RequirePkce": false
          }
        ]
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId": "1",
            "Username": "test",
            "Password": "test",
            "Claims": [
              {
                "Type": "name",
                "Value": "test"
              },
              {
                "Type": "email",
                "Value": "test@example.com"
              },
              {
                "Type": "email_verified",
                "Value": true
              },
              {
                "Type": "preferred_username",
                "Value": "test"
              }
            ]
          }
        ]
```
> Notice I've defined two custom claims above; `name` and `preferred_username`.

Here's the `id_token`:
```python
{
    'amr': ['pwd'],
    'at_hash': 'IBXeLLcfPJPGnAGUmsudgA',
    'aud': 'shipshop',
    'auth_time': 1596564870,
    'email': 'test@example.com',
    'email_verified': 'True',
    'exp': 1596565170,
    'iat': 1596564870,
    'idp': 'local',
    'iss': 'http://mock-idp.docker:4014',
    'nbf': 1596564870,
    'nonce': '1jhAyqmvisvHxUj8JGjiu73vxt4JwqDr',
    'sid': '827658dc41ab9de2f8801c6ebd3ff29e',
    'sub': '1'
}
```
> Notice `name` and `preferred_username` are not present.

And the `/userinfo` response:
```python
{
    'email': 'test@example.com',
    'email_verified': 'True',
    'sub': '1'
}
```
> Notice `name` and `preferred_username` are not present.

I must be misunderstanding something, any help appreciated!

**Comment by AleF83** [comment]
Hey,
I'm not sure but maybe [here](https://stackoverflow.com/questions/44761058/how-to-add-custom-claims-to-access-token-in-identityserver4)  there is the answer.

If it's so currently this feature doesn't supported.
But it looks not difficult to implement `ProfileService` that will read user claims from the configuration.

**Comment by cgrass** [comment]
You need to upgrade to a newer package. i think it was v0.2.1 that added support for `IDENTITY_RESOURCES_INLINE`. then you can set up your config like:
`IDENTITY_RESOURCES_INLINE: |
         [
           {
            "Name": "scopename", "ClaimTypes": ["claimname"]
           }
         ]`
i'm not certain the Name of that resource is required to be the scope defined for the client, but that works for us.

**Comment by cgrass** [comment]
PS - if you also need the custom claim in the API scope, you'll need to implement `ProfileService` to inject the custom claim into the identity token.

**Comment by AleF83** [comment]
> You need to upgrade to a newer package. i think it was v0.2.1 that added support for `IDENTITY_RESOURCES_INLINE`. then you can set up your config like:
> `IDENTITY_RESOURCES_INLINE: | [ { "Name": "scopename", "ClaimTypes": ["claimname"] } ]`
> i'm not certain the Name of that resource is required to be the scope defined for the client, but that works for us.

I've added test/example for this: https://github.com/Soluto/oidc-server-mock/pull/38

**Comment by xadvfh** [comment]
> PS - if you also need the custom claim in the API scope, you'll need to implement ProfileService to inject the custom claim into the identity token.

@cgrass do you mean that the ability to inject custom claims into the id_token is not supported yet?

**Comment by xadvfh** [comment]
For anyone else having issues with this, you need to add `"AlwaysIncludeUserClaimsInIdToken": true` to your client configs

**Comment by cburmeister** [comment]
@xadvfh I have that set in my example above 🤔

**Comment by xadvfh** [comment]
yea that's where i got it from, thanks for that.  it's working for me now.

**Comment by AleF83** [comment]
@cburmeister
I released [new version](https://github.com/Soluto/oidc-server-mock/releases/tag/v0.3.0) with support for custom user claims.
It should be helpful for your case.

**Comment by cburmeister** [comment]
@AleF83 thanks for the response! I'd like to test this out but I can't seem to authenticate as any configured user when upgrading to 0.3.0. I am prompted to login repeatedly and there's a CORS related exception in the logs. Same configuration as above. 🤔

**Comment by AleF83** [comment]
@cburmeister 
Do you run the server with HTTPS?
Maybe it caused by SameSite issue? See https://github.com/Soluto/oidc-server-mock/issues/25 for more details.

**Comment by cburmeister** [comment]
@AleF83 only over HTTP in local dev environments. The `SameSite` issue is probably it! I can see that the cookie policies are different between 0.1.2 and 0.3.0. Is there a way to configure the `SameSite` policy to `Lax`?

**Comment by AleF83** [comment]
You can configure with env var `ASPNET_SERVICES_OPTIONS_INLINE` or `ASPNET_SERVICES_OPTIONS_PATH`
See here: https://github.com/Soluto/oidc-server-mock/blob/ef6aa9753725273dee9d17b3842899c38616e442/e2e/docker-compose.yml#L18

I should update the documentation...

**Comment by cburmeister** [comment]
@AleF83 is that configuration tested anywhere? Or is there any documentation on what values are accepted? I'm following the example from #45 but I can't seem to change them from the default `SameSite=None;`.

**Comment by AleF83** [comment]
I need to add documentation about this configuration. In general, it allows to set several ASPNET configurations.
There are calls to `AddCors`, `AddSession` and `AddAuthentication` methods under hood.

The env var value is deserialized to `AspNetOptions` class. (https://github.com/Soluto/oidc-server-mock/blob/ef6aa9753725273dee9d17b3842899c38616e442/src/Helpers/AspNetServicesHelper.cs#L10)

I just changed value of `SameSite` to "Lax" and I saw it sent to the `AddAuthentication` method.

I'm not sure if it solves the issue. What is your scenario? I didn't tested with `Lax` mode. So it's interesting :-)

**Comment by cburmeister** [comment]
@AleF83 can you share a sample configuration to change `SameSite` to `Lax`? Preferably a full working example.

Here's my `docker-compose.yaml`:
```yaml
  mock-idp:
    entrypoint: bash /docker-entrypoint.sh
    image: soluto/oidc-server-mock:0.3.0
    ports:
    - "4013:80"
    environment:
    - ASPNET_SERVICES_OPTIONS_PATH=/OpenIdConnectServerMock/aspnet-options.json
    - CLIENTS_CONFIGURATION_PATH=/OpenIdConnectServerMock/clients.json
    - USERS_CONFIGURATION_PATH=/OpenIdConnectServerMock/users.json
    volumes:
    - ./config/mock-idp/clients.json:/OpenIdConnectServerMock/clients.json
    - ./config/mock-idp/docker-entrypoint.sh:/docker-entrypoint.sh
    - ./config/mock-idp/users.json:/OpenIdConnectServerMock/users.json
    - ./config/mock-idp/aspnet-options.json:/OpenIdConnectServerMock/aspnet-options.json
```

Here's my `config/mock-idp/users.json`:
```json
[
  {
    "Password": "test",
    "SubjectId": "1",
    "Username": "test"
  }
]
```

Here's my `config/mock-idp/clients.json`:
```json
[
  {
    "AccessTokenLifetime": 3600,
    "AllowAccessTokensViaBrowser": true,
    "AllowOfflineAccess": true,
    "AllowPlainTextPkce": true,
    "AllowedGrantTypes": [
      "authorization_code",
      "refresh_token"
    ],
    "AllowedScopes": [
      "openid",
      "offline_access"
    ],
    "ClientId": "discogs",
    "ClientSecrets": [
      "bigproblem"
    ],
    "IdentityTokenLifetime": 3600,
    "RedirectUris": [
      "http://app.docker:5000/idp/auth"
    ],
    "RequirePkce": false
  }
]
```

Here's my `config/mock-idp/aspnet-options.json`:
```json
{
  "Authentication": {
    "idsrv": {
      "CookieAuthenticationOptions": {
        "Cookie": {
          "SameSite": "Lax"
        }
      }
    }
  },
  "Session": {
    "Cookie": {
      "SameSite": "Lax"
    }
  }
}
```

I can confirm that the container is reading the `ASPNET_SERVICES_OPTIONS` because it throws an exception if you set `SameSite` to any other value besides `None`, `Lax` or `Strict`, but every response cookie remains `SameSite=None;`:

![Screen Shot 2020-11-03 at 8 35 10 AM](https://user-images.githubusercontent.com/1633451/98013811-b2bac900-1daf-11eb-80d9-be837a2e7642.png)

Any help would be much appreciated!
