### ISSUE TITLE
Container shows as (health: starting) for 60 seconds before switching to "healthy"

### ISSUE THREAD

**Issue by mjustin** [Soluto/oidc-server-mock#93]
I'm working on a project which uses this mock server.  It spins up this and a number of other docker containers and waits for all Docker containers to become healthy before moving on.  The `oidc-server-mock` is always the last to report as healthy.  It appears to always wait a full 60 seconds before doing so.  This means a process that should probably take about 10 seconds is actually taking a full minute.

I would expect this container to instead report healthy as soon as it up and running and ready to accept requests.

## Example

**`docker-compose.yml`**
```yaml
version: '3'
services:
  oidc-server-mock:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:latest
    ports:
      - "4011:80"
    volumes:
      - .:/tmp/config:ro
    environment:
      CLIENTS_CONFIGURATION_PATH: /tmp/config/clients-config.json
```

**`clients-config.json`**
```json
[
  {
    "ClientId": "client-credentials-mock-client",
    "ClientSecrets": [
      "client-credentials-mock-client-secret"
    ],
    "Description": "Client for client credentials flow",
    "AllowedGrantTypes": [
      "client_credentials"
    ],
    "AllowedScopes": [
      "some-app"
    ],
    "ClientClaimsPrefix": "",
    "Claims": [
      {
        "Type": "string_claim",
        "Value": "string_claim_value"
      },
      {
        "Type": "json_claim",
        "Value": "['value1', 'value2']",
        "ValueType": "json"
      }
    ]
  }
]
```

**`Command`**
```
docker-compose up
```

**`docker ps`**
```
watch "docker ps --format \"table {{.ID}}\t{{.Status}}\""
```

```
CONTAINER ID   STATUS
1234567890ab   Up 59 seconds (health: starting)
```

=>

```
CONTAINER ID   STATUS
1234567890ab   Up About a minute (healthy)
```

**Comment by mjustin** [comment]
Digging into this further, I suspect it's this configuration:

https://github.com/Soluto/oidc-server-mock/blob/master/src/Dockerfile#L34-L35

However, it looks like the `HEALTHCHECK` value is used both for the initial health check, as well as during the life of the container, so in general setting the value too low would also not be ideal.  Though maybe `curl -f http://localhost/health || exit 1` is inexpensive enough that it could reasonably be run far more frequently without any ill effects?

**Comment by mjustin** [comment]
I was able to workaround this in my application by lowering the health check of this container in my Docker compose file:

```yaml
version: '3'
services:
  oidc-server-mock:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:latest
    ports:
      - "4011:80"
    volumes:
      - .:/tmp/config:ro
    environment:
      CLIENTS_CONFIGURATION_PATH: /tmp/config/clients-config.json
    healthcheck:
      interval: 5s #Don't delay startup by the 60s configured for this container
      start_period: 60s
```
